version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pokemontcg_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=PokemonTCG;User=sa;Password=Admin2025!;
    depends_on:
      - db

  client:
    build:
      context: ./PokemonTCG.Web.Client
      dockerfile: Dockerfile.client
    container_name: pokemontcg_client
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pokemontcg_db
    environment:
      SA_PASSWORD: "Admin2025!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - pokemontcg_data:/var/opt/mssql

volumes:
  pokemontcg_data:
