// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonTCG.API.Data;

#nullable disable

namespace PokemonTCG.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027234826_DeckCardFix")]
    partial class DeckCardFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonTCG.API.Models.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityId"));

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbilityId");

                    b.HasIndex("CardId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.AncientTrait", b =>
                {
                    b.Property<int>("AncientTraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AncientTraitId"));

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AncientTraitId");

                    b.HasIndex("CardId");

                    b.ToTable("AncientTraits");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Attack", b =>
                {
                    b.Property<int>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttackId"));

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConvertedEnergyCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Damage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttackId");

                    b.HasIndex("CardId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Card", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardImageId")
                        .HasColumnType("int");

                    b.Property<int?>("ConvertedRetreatCost")
                        .HasColumnType("int");

                    b.Property<string>("EvolvesFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolvesTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hp")
                        .HasColumnType("int");

                    b.Property<int?>("LegalitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalPokedexNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RegulationMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetreatCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Types")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardId");

                    b.HasIndex("CardImageId")
                        .IsUnique()
                        .HasFilter("[CardImageId] IS NOT NULL");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("LegalitiesId")
                        .IsUnique()
                        .HasFilter("[LegalitiesId] IS NOT NULL");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardImage", b =>
                {
                    b.Property<int>("CardImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardImageId"));

                    b.Property<string>("Large")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Small")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardImageId");

                    b.ToTable("CardImages");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardMarket", b =>
                {
                    b.Property<int>("CardMarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardMarketId"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardMarketId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("CardMarkets");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardMarketPrice", b =>
                {
                    b.Property<int>("CardMarketId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageDayReverseHolo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageMonthReverseHolo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageSellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageWeekReverseHolo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardMarketPriceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LowPriceExPlus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReverseHoloLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReverseHoloTrend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrendPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CardMarketId");

                    b.ToTable("CardMarketPrices");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.DeckCard", b =>
                {
                    b.Property<int>("DeckCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckCardId"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DeckCardId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Legality", b =>
                {
                    b.Property<int>("LegalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalityId"));

                    b.Property<string>("Expanded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unlimited")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegalityId");

                    b.ToTable("Legalities");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<double?>("DirectLow")
                        .HasColumnType("float");

                    b.Property<double?>("High")
                        .HasColumnType("float");

                    b.Property<double?>("Low")
                        .HasColumnType("float");

                    b.Property<double?>("Market")
                        .HasColumnType("float");

                    b.Property<double?>("Mid")
                        .HasColumnType("float");

                    b.Property<int>("TCGPlayerPriceId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PriceId");

                    b.HasIndex("TCGPlayerPriceId", "Type")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Resistance", b =>
                {
                    b.Property<int>("ResistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResistanceId"));

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResistanceId");

                    b.HasIndex("CardId");

                    b.ToTable("Resistances");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Set", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ImagesId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PrintedTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("PtcgoCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetId");

                    b.HasIndex("ImagesId");

                    b.HasIndex("LegalitiesId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.SetImage", b =>
                {
                    b.Property<int>("SetImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetImageId"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetImageId");

                    b.ToTable("SetImages");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayer", b =>
                {
                    b.Property<int>("TCGPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TCGPlayerId"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TCGPlayerId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("TCGPlayers");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayerPrice", b =>
                {
                    b.Property<int>("TCGPlayerPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TCGPlayerPriceId"));

                    b.Property<int>("TCGPlayerId")
                        .HasColumnType("int");

                    b.HasKey("TCGPlayerPriceId");

                    b.HasIndex("TCGPlayerId");

                    b.ToTable("TCGPlayerPrices");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Weakness", b =>
                {
                    b.Property<int>("WeaknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaknessId"));

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaknessId");

                    b.HasIndex("CardId");

                    b.ToTable("Weaknesses");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Ability", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany("Abilities")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.AncientTrait", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Attack", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany("Attacks")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Card", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.CardImage", "CardImage")
                        .WithOne("Card")
                        .HasForeignKey("PokemonTCG.API.Models.Card", "CardImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTCG.API.Models.Legality", "Legalities")
                        .WithOne()
                        .HasForeignKey("PokemonTCG.API.Models.Card", "LegalitiesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTCG.API.Models.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardImage");

                    b.Navigation("Legalities");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardMarket", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithOne("CardMarket")
                        .HasForeignKey("PokemonTCG.API.Models.CardMarket", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardMarketPrice", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.CardMarket", "CardMarket")
                        .WithMany("CardMarketPrices")
                        .HasForeignKey("CardMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardMarket");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.DeckCard", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonTCG.API.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Price", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.TCGPlayerPrice", "TCGPlayerPrice")
                        .WithMany("Prices")
                        .HasForeignKey("TCGPlayerPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TCGPlayerPrice");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Resistance", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany("Resistances")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Set", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.SetImage", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesId");

                    b.HasOne("PokemonTCG.API.Models.Legality", "Legalities")
                        .WithMany()
                        .HasForeignKey("LegalitiesId");

                    b.Navigation("Images");

                    b.Navigation("Legalities");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayer", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithOne("Tcgplayer")
                        .HasForeignKey("PokemonTCG.API.Models.TCGPlayer", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayerPrice", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.TCGPlayer", "TCGPlayer")
                        .WithMany("TCGPlayerPrices")
                        .HasForeignKey("TCGPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TCGPlayer");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Weakness", b =>
                {
                    b.HasOne("PokemonTCG.API.Models.Card", "Card")
                        .WithMany("Weaknesses")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Card", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Attacks");

                    b.Navigation("CardMarket")
                        .IsRequired();

                    b.Navigation("DeckCards");

                    b.Navigation("Resistances");

                    b.Navigation("Tcgplayer")
                        .IsRequired();

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardImage", b =>
                {
                    b.Navigation("Card")
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Models.CardMarket", b =>
                {
                    b.Navigation("CardMarketPrices");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayer", b =>
                {
                    b.Navigation("TCGPlayerPrices");
                });

            modelBuilder.Entity("PokemonTCG.API.Models.TCGPlayerPrice", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
